/*
 * This source file was generated by the Gradle 'init' task
 */
package org.aph

import kotlin.test.Test

class WorkDialogServiceTest {
    @Test fun normalWorkFlow() {
        val workDialog = WorkDialogService()
        workDialog.open(title = "Test title", message = "Test message")
        workDialog.doWork { updater ->
            updater(100)
        }
        workDialog.close()
    }
}
